// Прогон разбора писем из Код.gs в чистом node: подменяем Google-объекты.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const src = fs.readFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '_intake', 'Код.gs'), 'utf8');
const store = {};
const PropertiesService = { getScriptProperties: () => ({ getProperties: () => ({ ...store }), getProperty: k => store[k] ?? null, setProperty: (k, v) => { store[k] = v; }, deleteProperty: k => { delete store[k]; } }) };
const Utilities = { formatDate: (d) => d.toISOString().slice(0, 7) };
const Logger = { log: () => {} };
const fn = new Function('PropertiesService', 'Utilities', 'Logger', src + '\nreturn { разборТаблицы, разборПодписей, телефон, запомнить, обработанные, почиститьПамять };');
const G = fn(PropertiesService, Utilities, Logger);
let pass = 0, fail = 0;
const eq = (n, got, want) => { const ok = JSON.stringify(got) === JSON.stringify(want); ok ? pass++ : fail++; console.log((ok ? 'ok   ' : 'FAIL ') + n + (ok ? '' : ' got ' + JSON.stringify(got))); };
const html = '<table><tr><td>Rob jones</td><td>Collection for Shelter Cymru</td><td>Collection from 20, Windsor place Abertidwr CF834DR</td><td>rob@example.com</td><td>No of bags = 15</td></tr><tr><td>Ann</td><td>Collection for No preference</td><td>Collection from 9 Dan Y Gollen, Crickhowell NP81TN</td><td>+44 (0)7700 900123</td><td>No of bags = 4 to 10</td></tr></table>';
const t = G.разборТаблицы('m1', html);
eq('table rows', t.length, 2);
eq('table addr 1', t[0].text, '20, Windsor place Abertidwr CF834DR');
eq('table email-only phone empty', t[0].phone, '');
eq('table charity', t[0].charity, 'Shelter Cymru');
eq('table bags', t[1].bags_text, '4 to 10');
eq('table +44 (0) phone normalised', t[1].phone, '+44 7700 900123');
const body = 'From: Sam Lee <sam@x.org>\nPhone: 01443 123456\nCollection address: 10 Bridgewater Road, Sully Penarth CF645RE\nQuantity of bags: 6\nChosen charity: Fire Fighters';
const f = G.разборПодписей('m2', body);
eq('fields rows', f.length, 1);
eq('fields landline', f[0].phone, '01443 123456');
eq('fields charity', f[0].charity, 'Fire Fighters');
eq('fields name', f[0].contact_name, 'Sam Lee');
eq('телефон +44 (0)', G.телефон('call +44 (0)7446 932887 pls'), '+44 7446 932887');
G.запомнить('abc'); G.запомнить('abc'); G.запомнить('def');
eq('memory dedupe', Object.keys(G.обработанные()).sort(), ['abc', 'def']);
console.log(`${pass} ok, ${fail} fail`); process.exit(fail ? 1 : 0);
